name: luma_mobile
description: "Luma Production Dating App Mobile Client"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  flutter_card_swiper: ^7.0.0
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
